-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.person
(
    id integer NOT NULL DEFAULT nextval('person_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(50) COLLATE pg_catalog."default" NOT NULL,
    phonenumber character varying(50) COLLATE pg_catalog."default" NOT NULL,
    city character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT person_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.request
(
    id integer NOT NULL DEFAULT nextval('request_id_seq'::regclass),
    personid integer,
    song character varying(50) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default",
    "time" timestamp without time zone NOT NULL,
    CONSTRAINT request_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.request
    ADD CONSTRAINT request_personid_fkey FOREIGN KEY (personid)
    REFERENCES public.person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;