-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.animal_size
(
    id integer NOT NULL DEFAULT nextval('animal_size_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    size double precision NOT NULL,
    CONSTRAINT animal_size_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.animal_size_weight
(
    id integer NOT NULL DEFAULT nextval('animal_size_weight_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    size double precision NOT NULL,
    weight double precision NOT NULL,
    CONSTRAINT animal_size_weight_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cities
(
    id integer NOT NULL DEFAULT nextval('cities_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default",
    num_companies integer,
    num_employees integer,
    CONSTRAINT cities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.city_population_area
(
    id integer NOT NULL DEFAULT nextval('city_population_area_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    population integer NOT NULL,
    area double precision NOT NULL,
    CONSTRAINT city_population_area_pkey PRIMARY KEY (id)
);
END;